-- CREATE DATABASE VetMate; GO
-- USE VetMate; GO

IF OBJECT_ID('Users','U') IS NULL
CREATE TABLE Users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(120) NOT NULL,
  email NVARCHAR(255) NOT NULL UNIQUE,
  password_hash NVARCHAR(255) NOT NULL,
  role NVARCHAR(50) NOT NULL DEFAULT 'user',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID('Pets','U') IS NULL
CREATE TABLE Pets (
  id INT IDENTITY(1,1) PRIMARY KEY,
  owner_id INT NOT NULL FOREIGN KEY REFERENCES Users(id) ON DELETE CASCADE,
  name NVARCHAR(120) NOT NULL,
  species NVARCHAR(60) NOT NULL,
  breed NVARCHAR(120) NULL,
  birthdate DATE NULL,
  notes NVARCHAR(1000) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID('Vets','U') IS NULL
CREATE TABLE Vets (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(120) NOT NULL,
  crmvet NVARCHAR(60) NULL,
  specialty NVARCHAR(120) NULL,
  phone NVARCHAR(60) NULL,
  email NVARCHAR(255) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

IF OBJECT_ID('Appointments','U') IS NULL
CREATE TABLE Appointments (
  id INT IDENTITY(1,1) PRIMARY KEY,
  pet_id INT NOT NULL FOREIGN KEY REFERENCES Pets(id) ON DELETE CASCADE,
  vet_id INT NULL FOREIGN KEY REFERENCES Vets(id) ON DELETE SET NULL,
  date_time DATETIME2 NOT NULL,
  reason NVARCHAR(500) NOT NULL,
  status NVARCHAR(40) NOT NULL DEFAULT 'scheduled',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE INDEX IX_Pets_Owner ON Pets(owner_id);
CREATE INDEX IX_Appointments_Date ON Appointments(date_time);
GO
